################################################################
# Global configuration
################################################################
global:
  checkNewVersion: true
  sendAnonymousUsage: false

################################################################
# API and dashboard configuration
################################################################
api:
  dashboard: true
  insecure: false # In production, secure this with a password
  
################################################################
# Entrypoints configuration
################################################################
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

################################################################
# Docker configuration
################################################################
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: translator_network

################################################################
# SSL certificate configuration
################################################################
certificatesResolvers:
  letsencryptResolver:
    acme:
      email: "your-email@example.com"
      storage: "/etc/traefik/acme/acme.json"
      tlsChallenge: {}

################################################################
# Log configuration
################################################################
log:
  level: "INFO"
  format: "common"

accessLog:
  format: "common"
